name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install bandit safety

    - name: Run Security Scans
      run: |
        bandit -r labs/
        safety check

    - name: Validate Labs
      run: |
        for lab in labs/*; do
          if [ -d "$lab" ]; then
            echo "Validating $(basename "$lab")..."
            # Add specific validation for each lab type
          fi
        done

    - name: Run Hooks
      run: |
        chmod +x scripts/hooks/pre-commit-init.sh
        find . -type f | grep -v '.git' | grep -v '.venv' | xargs -I {} bash scripts/hooks/pre-commit-init.sh {}
